<a href="https://colab.research.google.com/github/mondjisola/dpro_divic/blob/master/Matrix_product_implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[Problem 1] Matrix product is calculated manually

In [ ]:
import numpy as np

$$
A = \begin{bmatrix}
-1 & 2 & 3 \\
4 & -5 & 6 \\
7 & 8 & -9
\end{bmatrix}
$$

In [ ]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])

$$
B = \begin{bmatrix}
0 & 2 & 1 \\
0 & 2 & -8 \\
2 & 9 & -1
\end{bmatrix}
$$

In [ ]:
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

The number of columns in $A(3, 3)$ is equal to the number of rows in $B(3, 3)$, so they are compatible for multiplication and the product $AB$ is defined. Then, the product of $A$ and $B$ (denoted as $AB$) is a new matrix $C$(3,3).

In [ ]:
c_ndarray = np.zeros((a_ndarray.shape[0], b_ndarray.shape[1])).astype(int)
m, n = c_ndarray.shape

The element at the ith row and jth column of $C$ (denoted as $cij$​
) is calculated as the *sum of the products of the corresponding elements from the ith row of $A$ and the jth column of $B$*:
$$
c_{ij} = a_{i1}b_{1j} + a_{i2}b_{2j} + a_{i3}b_{3j} = \sum_{k=1}^{3} a_{ik}b_{kj}
$$


In [ ]:
# for i in range(m):
#   for j in range(n):
#     c_ndarray[i, j] = np.sum(a_ndarray[i,:]*b_ndarray[:,j])
# c_ndarray
# refactorized as following
c_ndarray = np.array([[np.sum(a_ndarray[i,:]*b_ndarray[:,j]) for j in range(n)] for i in range(m)])

In [ ]:
print("The matrix product of A and B is: \n{}".format(c_ndarray))

The matrix product of A and B is: 
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


---

[Problem 2] Calculation by NumPy function

In [ ]:
c_ndarray_matmul = np.matmul(a_ndarray, b_ndarray)
c_ndarray_matmul

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [ ]:
c_ndarray_dot = np.dot(a_ndarray, b_ndarray)
c_ndarray_dot

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [ ]:
c_ndarray_at = a_ndarray@b_ndarray
c_ndarray_at

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

---

[Problem 3] Implementation of calculation of a certain element

The code to do the calculation of the row 0 of matrix $A$ and column 0 of matrix $B$ is:

```
np.sum(a[0,:]*b[:,0])
```

---

[Problem 4] Creating a function that performs matrix multiplication

In [ ]:
def matrix_product(a: np.ndarray, b: np.ndarray) -> np.ndarray:
  """A function that returns the matrix resulting of two 2D matrices a and b product calculation.

  Parameters
  -----------
  a: numpy.ndarray
      The first matrix.
  b: numpy.ndarray
      The second matrix.

  Returns
  -------
  numpy.ndarray
      The matrix product of a and b.
  """
  import numpy as np
  m, n = a.shape[0], b.shape[1]
  return np.array([[np.sum(a[i,:]*b[:,j]) for j in range(n)] for i in range(m)])

---

[Problem 5] Judge the input whose calculation is not defined

In [ ]:
def matrix_product(a: np.ndarray, b: np.ndarray) -> np.ndarray:
  """A function that returns the matrix resulting of two 2D matrices a and b product calculation.

  Parameters
  -----------
  a: numpy.ndarray
      The first matrix.
  b: numpy.ndarray
      The second matrix.

  Returns
  -------
  numpy.ndarray
      The matrix product of a and b.
  """
  import numpy as np

  if a.shape[1] != b.shape[0]:
    print("Error: The number of columns in the first matrix must be equal to the number of rows in the second matrix for matrix multiplication.")
    return None
  else:
    m, n = a.shape[0], b.shape[1]
    return np.array([[np.sum(a[i,:]*b[:,j]) for j in range(n)] for i in range(m)])

In [ ]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
matrix_product(d_ndarray, e_ndarray)

Error: The number of columns in the first matrix must be equal to the number of rows in the second matrix for matrix multiplication.


---

[Problem 6] Transposition

In [ ]:
f_ndarray = e_ndarray.T
matrix_product(d_ndarray, f_ndarray)

array([[ 46,  -4],
       [-34,  73]])